name: dbt CI/CD

on:
  push:
    branches:
      - main  # Déclenchement sur push vers la branche principale
  pull_request:  # Déclenchement sur les PR
    branches:
      - main

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
    # 1. Configurer le dépôt
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Installer Python et dbt
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dbt
      run: |
        pip install dbt-postgres==1.9.1  # Remplacez par l'adaptateur approprié
        pip install -r requirements.txt

    # 3. Configuration du fichier profiles.yml
    - name: Set up dbt profiles
      run: |
        mkdir ~/.dbt
        echo "${{ secrets.DBT_PROFILE }}" > ~/.dbt/profiles.yml

    # 4. Installer les dépendances dbt
    - name: Install dbt packages
      run: dbt deps

    # 5. Tests dbt
    - name: Run dbt tests
      run: |
        dbt debug  # Valide la connexion à l'entrepôt
        dbt test   # Exécute les tests

    # 6. Exécution des modèles dbt
    - name: Run dbt models
      run: |
        dbt run

    # 7. Génération de la documentation dbt
    - name: Generate dbt docs
      run: |
        dbt docs generate
