name: dbt CD for dbt_sales

on:
  push:
    branches:
      - main  # Déploiement sur la branche principale

jobs:
  dbt-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupérer le code source
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurer Python et dbt
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dbt and dependencies
      run: |
        pip install dbt-postgres==1.9.1  # Remplacez par l'adaptateur approprié
        pip install -r requirements.txt

    # 3. Configurer les informations de connexion dbt
    - name: Set up dbt profiles
      run: |
        mkdir ~/.dbt
        echo "${{ secrets.DBT_PROFILE_PROD }}" > ~/.dbt/profiles.yml

    # 4. Installer les dépendances dbt
    - name: Install dbt packages
      run: dbt deps

    # 5. Exécuter les modèles dbt pour l'environnement de production
    - name: Run dbt models for production
      run: |
        dbt run --target prod             # Exécute les modèles pour l'environnement de production

    # 6. Tests finaux (optionnel)
    - name: Run dbt tests in production
      run: |
        dbt test --targe
