name: dbt CI/CD for dbt_sales

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt-ci-cd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dbt and dependencies
      run: |
        pip install dbt-core==1.9.1
        pip install dbt-postgres==1.9.0

    - name: Set up dbt profiles
      run: |
        mkdir ~/.dbt
        echo "${{ secrets.DBT_PROFILE_DEV }}" > ~/.dbt/profiles.yml

    - name: Install dbt packages
      run: dbt deps

    - name: Test dbt connection
      run: dbt debug

    - name: Validate schemas
      run: |
        psql -U postgres -h localhost -d sales -c "SELECT schema_name FROM information_schema.schemata WHERE schema_name IN ('public', 'public_staging', 'public_marts', 'snapshots');"

    - name: Run dbt snapshots
      run: dbt snapshot --target dev

    - name: Run dbt tests
      run: dbt test --target dev

    - name: Run dbt models (incremental)
      run: dbt run --selector incremental

    - name: Generate dbt documentation
      run: dbt docs generate

    - name: Upload dbt documentation artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dbt-docs
        path: target/


